// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yiclipdmvnetgsttexab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpY2xpcGRtdm5ldGdzdHRleGFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MjY2MDQsImV4cCI6MjA2OTQwMjYwNH0.VYtnRlwWnpxp8BqA-pAVONdm22u34Bv8tvEnPlCxYHs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});